"""Ancient Cities Modding Kit public Python API."""

from __future__ import annotations

from ._version import (
    PROJECT_SCHEMA_VERSION,
    REPORT_SCHEMA_VERSION,
    RUNTIME_TEST_SCHEMA_VERSION,
    SDK_API_VERSION,
    __version__,
)
from .builder import DraftProjectBuilder, DraftProjectPlan, DraftProjectResult, PlannedContent
from .building import (
    BuildingAssetPath,
    BuildingModel,
    BuildingScaffoldBuilder,
    BuildingScaffoldPlan,
    BuildingScaffoldResult,
    BuildingSpec,
    ConstructionStage,
    DecayStage,
)
from .config import (
    AchievementImpact,
    Compatibility,
    ProjectConfig,
    ProjectPaths,
    ProvenanceStatus,
    RuntimeSaveType,
    RuntimeStatus,
    SaveImpact,
    SavePersistence,
    SkeletonSource,
)
from .errors import (
    ACMKError,
    ContractError,
    LegacyModToolError,
    ProjectError,
    SourceChangedError,
    UnsafePathError,
    ValidationFailedError,
)
from .knowledge import (
    KnowledgeDocument,
    KnowledgeError,
    KnowledgeTopic,
    SearchHit,
    UnknownTopicError,
)
from .knowledge import (
    read as read_knowledge,
)
from .knowledge import (
    search as search_knowledge,
)
from .knowledge import (
    topics as knowledge_topics,
)
from .manifest import (
    GameVersion,
    ManifestDocument,
    ManifestSpec,
    NewlineStyle,
    SteamModId,
    TextAssetKind,
    Utf16TextDocument,
)
from .paths import AncientPath, EngineReference, ProjectRelativePath
from .project import (
    FileSnapshot,
    ObservedConsensusPlan,
    ObservedConsensusResult,
    ProjectConfigPlan,
    ProjectConfigResult,
    ProjectImporter,
    ProjectImportPlan,
    ProjectImportResult,
    ProjectLayout,
    ReleasePlan,
    ReleaseResult,
    RuntimeTestPlan,
    RuntimeTestResult,
    SDKProject,
    SourceFingerprint,
    StagedArtifact,
)
from .reports import (
    CheckStatus,
    DiscoverySnapshot,
    DoctorCheck,
    DoctorReport,
    ExecutionMode,
    Issue,
    Severity,
    ValidationProfile,
    ValidationReport,
    envelope,
)
from .sdk import AncientCitiesSDK, DiscoveryOptions
from .workshop import (
    PUBLISH_PACKET_SCHEMA_VERSION,
    WORKSHOP_APP_ID,
    WORKSHOP_STATE_SCHEMA_VERSION,
    CandidateKind,
    PublishAction,
    PublishPacket,
    VisibilityControl,
    WorkshopArtifact,
    WorkshopState,
    WorkshopStatus,
    WorkshopSyncPlan,
    WorkshopSyncResult,
    WorkshopVisibility,
    plan_workshop_sync,
    prepare_publish_packet,
)

__all__ = [
    "ACMKError",
    "AchievementImpact",
    "AncientCitiesSDK",
    "AncientPath",
    "BuildingAssetPath",
    "BuildingModel",
    "BuildingScaffoldBuilder",
    "BuildingScaffoldPlan",
    "BuildingScaffoldResult",
    "BuildingSpec",
    "CandidateKind",
    "CheckStatus",
    "Compatibility",
    "ContractError",
    "ConstructionStage",
    "DecayStage",
    "DiscoveryOptions",
    "DiscoverySnapshot",
    "DoctorCheck",
    "DoctorReport",
    "DraftProjectBuilder",
    "DraftProjectPlan",
    "DraftProjectResult",
    "EngineReference",
    "ExecutionMode",
    "FileSnapshot",
    "GameVersion",
    "Issue",
    "KnowledgeDocument",
    "KnowledgeError",
    "KnowledgeTopic",
    "LegacyModToolError",
    "ManifestDocument",
    "ManifestSpec",
    "NewlineStyle",
    "ObservedConsensusPlan",
    "ObservedConsensusResult",
    "PROJECT_SCHEMA_VERSION",
    "PUBLISH_PACKET_SCHEMA_VERSION",
    "PlannedContent",
    "PublishAction",
    "PublishPacket",
    "ProjectConfig",
    "ProjectConfigPlan",
    "ProjectConfigResult",
    "ProjectError",
    "ProjectImportPlan",
    "ProjectImportResult",
    "ProjectImporter",
    "ProjectLayout",
    "ProjectPaths",
    "ProjectRelativePath",
    "ProvenanceStatus",
    "REPORT_SCHEMA_VERSION",
    "RUNTIME_TEST_SCHEMA_VERSION",
    "ReleasePlan",
    "ReleaseResult",
    "RuntimeStatus",
    "RuntimeSaveType",
    "SavePersistence",
    "RuntimeTestPlan",
    "RuntimeTestResult",
    "SDKProject",
    "SDK_API_VERSION",
    "SaveImpact",
    "SearchHit",
    "Severity",
    "SkeletonSource",
    "SourceFingerprint",
    "StagedArtifact",
    "SourceChangedError",
    "SteamModId",
    "TextAssetKind",
    "UnsafePathError",
    "UnknownTopicError",
    "Utf16TextDocument",
    "ValidationFailedError",
    "ValidationProfile",
    "ValidationReport",
    "VisibilityControl",
    "WORKSHOP_APP_ID",
    "WORKSHOP_STATE_SCHEMA_VERSION",
    "WorkshopArtifact",
    "WorkshopState",
    "WorkshopStatus",
    "WorkshopSyncPlan",
    "WorkshopSyncResult",
    "WorkshopVisibility",
    "__version__",
    "envelope",
    "knowledge_topics",
    "plan_workshop_sync",
    "prepare_publish_packet",
    "read_knowledge",
    "search_knowledge",
]
